{"uuid": "90d4971b-b905-4c1d-bf61-020f8448f0b4", "children": ["a5a9c486-f0b0-4505-891a-b7cdaec7306a"], "befores": [{"name": "stop", "status": "passed", "start": 1680158460374, "stop": 1680158460374}], "afters": [{"name": "stop::fin", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=111.0.5563.112)\nStacktrace:\nBacktrace:\n\t(No symbol) [0x00CCDCE3]\n\t(No symbol) [0x00C639D1]\n\t(No symbol) [0x00B74DA8]\n\t(No symbol) [0x00B5D0D3]\n\t(No symbol) [0x00BBEA8B]\n\t(No symbol) [0x00BCD093]\n\t(No symbol) [0x00BBACC6]\n\t(No symbol) [0x00B96F68]\n\t(No symbol) [0x00B980CD]\n\tGetHandleVerifier [0x00F43832+2506274]\n\tGetHandleVerifier [0x00F79794+2727300]\n\tGetHandleVerifier [0x00F7E36C+2746716]\n\tGetHandleVerifier [0x00D76690+617600]\n\t(No symbol) [0x00C6C712]\n\t(No symbol) [0x00C71FF8]\n\t(No symbol) [0x00C720DB]\n\t(No symbol) [0x00C7C63B]\n\tBaseThreadInitThunk [0x750200F9+25]\n\tRtlGetAppContainerNamedObjectPath [0x77017BBE+286]\n\tRtlGetAppContainerNamedObjectPath [0x77017B8E+238]\n\n", "trace": "  File \"C:\\Devel\\python_test\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\Devel\\python_test\\conftest.py\", line 29, in fin\n    fixture.session.logout()\n  File \"C:\\Devel\\python_test\\fixture\\session.py\", line 30, in logout\n    wd.find_element(By.CSS_SELECTOR, \"body\").send_keys(Keys.HOME)\n  File \"C:\\Devel\\python_test\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 861, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n  File \"C:\\Devel\\python_test\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 444, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Devel\\python_test\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 249, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1680158482522, "stop": 1680158486613}], "start": 1680158460374, "stop": 1680158486613}